In [5]:
import numpy as np
import pandas as pd








In [6]:
#Exercise 1: Create two dimensional 3*3 array and perform ndim, shape, slicing operation on it.

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d.ndim)
print(arr2d.shape)
print(arr2d[1:,1:])

2
(3, 3)
[[5 6]
 [8 9]]


In [7]:
#Exercise 2 : Create one dimensional array and perform ndim, shape, reshape operation on it.

arr1d = np.array([10, 20, 30, 40, 50, 60])
print(arr1d.ndim)
print(arr1d.shape)
new_arr = arr1d.reshape(2, 3)
print(new_arr)

1
(6,)
[[10 20 30]
 [40 50 60]]


In [8]:
"""Exercise 3: Pandas-DataFrame
Download the data set and rename to cars.csv
   a. Import Pandas
   b. Import the Cars Dataset and store the Pandas DataFrame in the variable cars
   c. Inspect the first 10 Rows of the DataFrame cars
   d. Inspect the DataFrame cars by "printing" cars
   e. Inspect the last 5 Rows
   f. Get some meta information on our DataFrame!"""

cars = pd.read_csv("auto-mpg.csv")
print(cars.head(10))
print(cars)
print(cars.tail(5))
print(cars.info())

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skyla

In [9]:

"""Exercise 4 :  Download 50_startups dataset                                                                                                                           Link  : https://www.kaggle.com/datasets/farhanmd29/50-startups  
a.  Create DataFrame using Pandas
b.  Read the data from 50_startups.csv file and load the data into dataframe.
c.  Check the statistical summary.
d. Check for corelation coefficient between dependent and independent variables."""

startups = pd.read_csv("50_Startups.csv")
print(startups)
print(startups.describe())
print(startups.select_dtypes(include=['number']).corr())


    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       